import Head from 'next/head'
import CommentForm from '../components/CommentForm';
import Comments from '../components/Comments';
//import Comments from '../components/Comments';
import { useComment } from '../context/commentsContext';

export default function Home() {
  const {data} = useComment();
  //console.log(state);
  return (
    <div className="px-20 my-10 ">
      <Head>
        <title>Fridom Prueba Stefano Quiroz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/fridom.ico" />
      </Head>

      <CommentForm/>

      {data.length === 0 ? (' ') : (
        <h1 className="font-black">Comentarios anteriores ({data.length})</h1>
      )}
      
      <Comments />



      
      {/* CommentForm */}
      {/* CommentList */}

      
    </div>
  )
}
